repository: "jboss/tyr"
statusUrl: "https://raw.githubusercontent.com/jboss/tyr/master/.github/tyr-format.yaml"

format:
  skipPatterns:
    description: "(([^do not|don't]\\s)?skip.*template.*check(.*)\\s?)|(([^do not|don't]\\s)?bypass.*template.*check(.*)\\s?)"
  description:
    required rows:
      - pattern: "\\b(close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)\\b\\s#\\d+\\s*"
        message: "The PR description must contain a link to the GitHub issue it is resolving"
