name: Tyr CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    name: JDK ${{matrix.java-version}} JVM build and tests
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        java-version: [8, 11]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java-version }}
      # Uses sha for added security since tags can be updated
      uses: joschi/setup-jdk@b9cc6eabf7e7e3889766b5cee486f874c9e1bd2d
      with:
        java-version: ${{ matrix.java-version }}
    - name: Build with Maven
      run: eval mvn clean install

